# Generated by Django 4.2.16 on 2025-11-26 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dataset_size", models.IntegerField()),
                ("mean_value", models.FloatField()),
                ("median_value", models.FloatField()),
                ("std_deviation", models.FloatField()),
                ("min_value", models.FloatField()),
                ("max_value", models.FloatField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-computed_at"],
            },
        ),
        migrations.CreateModel(
            name="DataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="sample_app__created_23cdaa_idx"
                    ),
                    models.Index(fields=["value"], name="sample_app__value_92d606_idx"),
                ],
            },
        ),
    ]
